# Generated by Django 4.2.7 on 2023-12-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_task_date_remove_task_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create',
        ),
    ]
