# Generated by Django 4.2.7 on 2023-12-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_alter_task_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', 'date']},
        ),
    ]
