# Generated by Django 4.2.7 on 2024-05-09 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 9), null=True),
        ),
    ]
